function plotLogMarginalLikelihood(phi_y,n_samp,phi_y_mean) 

% plot the log-likelihood and its moving average for all samples

figure;

subplot(2,1,1)
plot(phi_y(1:n_samp))
hYLabel1  = ylabel("log-likelihood");
ax1       = gca;

subplot(2,1,2)
plot(phi_y_mean)

ax2       = gca;
ax        = [ax1 ax2];
hXLabel   = xlabel("Sample number");
hYLabel2  = ylabel("moving average log-likelihood");
hYLabel   = [hYLabel1 hYLabel2];
fs        = 12;
set( ax                       , ...
    'FontName'   , 'Times New Roman', ...
    'FontSize'   , fs);
set(hXLabel, ...
    'FontName'   , 'Times New Roman', ...
    'FontSize'   , fs);
set(hYLabel, ...
    'FontName'   , 'Times New Roman', ...
    'FontSize'   , fs);
set(ax, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'in'     , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XColor'      , [0 0 0], ...
    'YColor'      , [0 0 0], ...
    'LineWidth'   , 0.5         );

end