function plotResiduals(nor,x,y,nx,ny,x_lab,y_lab,x_min,x_max,...
    z_min,z_max,varargin)

% plot histogram of decorrelated residuals
figure
hold on
subplot(1,2,1)
histogram2(x,y,[nx ny],'DisplayStyle','tile','ShowEmptyBins','on',...
    'Normalization',nor); colormap sky; colorbar('northoutside');

%figure properties
% axis tight
ax = gca;
ax.YDir = 'reverse';
xlim([x_min(1) x_max(1)]);
ax.YLim  = [z_min z_max];
ax.YTick = [0:2:z_max];
xlab = sprintf('{%s}',x_lab);
ylab = sprintf('{%s}',y_lab);
hXLabel = xlabel(xlab);
hYLabel = ylabel(ylab);
fs = 12;
set( ax                       , ...
    'FontName'   , 'Times New Roman', ...
    'FontSize'   , fs);
set(hXLabel, ...
    'FontName'   , 'Times New Roman', ...
    'FontSize'   , fs);
set(hYLabel, ...
    'FontName'   , 'Times New Roman', ...
    'FontSize'   , fs);
set(ax, ...
    'Box'         , 'on'     , ...
    'TickDir'     , 'in'     , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'YGrid'       , 'off'      , ...
    'XColor'      , [0 0 0], ...
    'YColor'      , [0 0 0], ...
    'LineWidth'   , 0.5         );

hold off

if varargin{1,1}{1,1} == 1
    x_mat         = varargin{1,1}{1,2};
    nbins         = varargin{1,1}{1,3};
    col_prior     = varargin{1,1}{1,4};
    col_hist      = varargin{1,1}{1,5};
    lw            = varargin{1,1}{1,6};
    x0            = varargin{1,1}{1,7};
    y0            = varargin{1,1}{1,8};
    width         = varargin{1,1}{1,9};
    height        = varargin{1,1}{1,10};

    x_mat_mean    = mean(x_mat,2);

    % plot histogram of average decorrelated residuals
    subplot(1,2,2)

    hold on
    histogram(x_mat_mean,nbins,'Normalization',nor,'FaceColor',col_prior,...
        'EdgeColor','none');
    [den_mean,xi_mean] = ksdensity(x_mat_mean);
    plot(xi_mean,den_mean,'LineWidth',lw,'Color',col_hist,'LineStyle','-');
    xlim([x_min(1) x_max(1)]);
    [den,xi] = ksdensity(randn(size(x_mat,1)*size(x_mat,2),1));
    plot(xi,den,'--','LineWidth',lw,'Color',[0.45 0.45 0.45])
    xlab = sprintf('{%s}',x_lab);
    hXLabel = xlabel(xlab);
    ax = gca;
    set( ax                       , ...
        'FontName'   , 'Times New Roman', ...
        'FontSize'   , fs);
    set(hXLabel, ...
        'FontName'   , 'Times New Roman', ...
        'FontSize'   , fs);
    set(ax, ...
        'Box'         , 'on'     , ...
        'TickDir'     , 'in'     , ...
        'TickLength'  , [.01 .01] , ...
        'XMinorTick'  , 'off'      , ...
        'YMinorTick'  , 'off'      , ...
        'YGrid'       , 'off'      , ...
        'XColor'      , [0 0 0], ...
        'YColor'      , [0 0 0], ...
        'LineWidth'   , 0.5         );

    hold off

    set(gcf,'units','centimeters','Position',[x0,y0,width,height]);
    set(gcf, 'PaperPositionMode', 'auto');

end

end
